### ISSUE TITLE
consumer `TransferProcesses` not Transitioning to Completed State

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#3334]
# Bug Report

## Describe the Bug

With the latest 0.2.0 version our tests are failing, because the consumer `transferprocess` is not transitioning to `Completed` state. This is caused by a missing `StatusChecker` implementation for `HttpData` type.

### Expected Behavior

Providing a default implementation for the `HttpData` `StatusChecker` or transition to `Completed` when there is no `StatusChecker` registered.

### Observed Behavior

Data successfully transfered, but consumer `transferprocesses` stuck in `Started` state.

## Context Information

- Used version EDC v0.2.0

## Detailed Description

Log:
No checker found for process d0fcaa06-2e81-466f-a95a-3debf49a0885. The process will not advance to the COMPLETED state.

https://github.com/eclipse-edc/Connector/blob/de80081d547c66f127dd32e1a8b27d9fca2d4410/core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java#L422-L433

**Comment by paullatzelsperger** [comment]
I've noticed that as well, we'll look into it.

**Comment by ndr-brt** [comment]
So, there are multiple things on this, is it true as I said that the data-plane should take care of that through the control api, but this can only work if these extensions are added to the runtime:
- `control-plane-api` on the control-plane
- `control-plane-api-client` on the data-plane

then there's a bug already filed here: #3377 
I will fix up this, then to have the transfer completed would be just a matter of having the extensions added to the runtime.

**Comment by timdahlmanns** [comment]
Is there more to do than just adding the two extensions to the runtime? With version 0.3.0 I still have the log output "No checker found..." and the transfer stays in STARTED state. Nevertheless, the transfer is successful as in https://github.com/eclipse-tractusx/tractusx-edc/issues/790

**Comment by wolf4ood** [comment]
Hi @timdahlmanns on which kind of transfer do you have this issue?

Adding those two extension should solve the issue.

**Comment by timdahlmanns** [comment]
Hi @wolf4ood, it is a http push transfer similar to the transfer-07 sample. For more details I attach the CP and DP dependencies as well as the logs of provider and consumer CP and DP.

Actually I overlooked the exception at the provider DP yesterday. Maybe this is the root problem? Did we forget to configure an API part since we didn't configure port 9191, that the provider DP tries to reach?

---

<details>
<summary>CP dependencies</summary>

```kts
dependencies {
  implementation("org.eclipse.edc:control-plane-core:0.3.0")
  implementation("org.eclipse.edc:dsp:0.3.0")
  implementation("org.eclipse.edc:configuration-filesystem:0.3.0")
  implementation("org.eclipse.edc:vault-filesystem:0.3.0")
  implementation("org.eclipse.edc:iam-mock:0.3.0")

  implementation("org.postgresql:postgresql:42.6.0")
  implementation("org.eclipse.edc:control-plane-sql:0.3.0")
  implementation("org.eclipse.edc:transaction-local:0.3.0")
  implementation("org.eclipse.edc:sql-pool-apache-commons:0.3.0")

  implementation("org.eclipse.edc:management-api:0.3.0")
  implementation("org.eclipse.edc:api-observability:0.3.0")
  implementation("org.eclipse.edc:control-plane-api:0.3.0")

  implementation("org.eclipse.edc:transfer-data-plane:0.3.0")
  implementation("org.eclipse.edc:data-plane-client:0.3.0")
  implementation("org.eclipse.edc:data-plane-selector-api:0.3.0")
  implementation("org.eclipse.edc:data-plane-selector-client:0.3.0")
  implementation("org.eclipse.edc:data-plane-selector-core:0.3.0")
  implementation("org.eclipse.edc:data-plane-selector-spi:0.3.0")
  implementation("org.eclipse.edc:jwt-core:0.3.0")
}
```
</details>

<details>
<summary>DP dependencies</summary>

```kts
  implementation("org.eclipse.edc:data-plane-core:0.3.0")

  implementation("org.eclipse.edc:data-plane-api:0.3.0")
  implementation("org.eclipse.edc:data-plane-http:0.3.0")
  implementation("org.eclipse.edc:http:0.3.0")
  implementation("org.eclipse.edc:api-observability:0.3.0")
  implementation("org.eclipse.edc:control-plane-api-client:0.3.0")

  implementation("org.eclipse.edc:configuration-filesystem:0.3.0")
```
</details>

---

<details>
<summary>Provider CP logs</summary>

```
[...]
DEBUG 2023-09-27T10:43:02.217910418 DSP: Incoming ContractRequestMessage for class org.eclipse.edc.connector.contract.spi.typ
DEBUG 2023-09-27T10:43:02.256985187 [PROVIDER] ContractNegotiation 52aa5fbe-2b80-4ca8-aec7-7484c851a84e is now in state REQUE
DEBUG 2023-09-27T10:43:02.430009297 [PROVIDER] ContractNegotiation 52aa5fbe-2b80-4ca8-aec7-7484c851a84e is now in state AGREEING.
DEBUG 2023-09-27T10:43:02.436715132 ContractNegotiation: ID 52aa5fbe-2b80-4ca8-aec7-7484c851a84e. [Provider] send agreement
DEBUG 2023-09-27T10:43:02.525869624 ContractNegotiation: ID 52aa5fbe-2b80-4ca8-aec7-7484c851a84e. [Provider] send agreement
DEBUG 2023-09-27T10:43:02.531727611 [PROVIDER] ContractNegotiation 52aa5fbe-2b80-4ca8-aec7-7484c851a84e is now in state AGREED.
DEBUG 2023-09-27T10:43:03.260075276 DSP: Incoming ContractAgreementVerificationMessage for class org.eclipse.edc.connector.contract.spi.types.negotiation.ContractNegotiation process: f99d59b4-16bc-4c81-a69e-28cb3809b7a0
DEBUG 2023-09-27T10:43:03.26877763 [PROVIDER] ContractNegotiation 52aa5fbe-2b80-4ca8-aec7-7484c851a84e is now in state VERIFIED.
DEBUG 2023-09-27T10:43:03.499554309 [PROVIDER] ContractNegotiation 52aa5fbe-2b80-4ca8-aec7-7484c851a84e is now in state FINALIZING.
DEBUG 2023-09-27T10:43:03.507464194 ContractNegotiation: ID 52aa5fbe-2b80-4ca8-aec7-7484c851a84e. [Provider] send finalization
DEBUG 2023-09-27T10:43:03.529896361 ContractNegotiation: ID 52aa5fbe-2b80-4ca8-aec7-7484c851a84e. [Provider] send finalization
DEBUG 2023-09-27T10:43:03.537149776 [PROVIDER] ContractNegotiation 52aa5fbe-2b80-4ca8-aec7-7484c851a84e is now in state FINALIZED.
DEBUG 2023-09-27T10:43:32.355673261 DSP: Incoming TransferRequestMessage for class org.eclipse.edc.connector.transfer.spi.types.TransferProcess process
DEBUG 2023-09-27T10:43:32.377032887 TransferProcess f745da66-3b04-4a51-a813-f570df298465 is now in state INITIAL
DEBUG 2023-09-27T10:43:32.901643775 TransferProcess f745da66-3b04-4a51-a813-f570df298465 is now in state PROVISIONING
DEBUG 2023-09-27T10:43:32.910717891 TransferProcess: ID f745da66-3b04-4a51-a813-f570df298465. Provisioning
DEBUG 2023-09-27T10:43:32.924731328 TransferProcess f745da66-3b04-4a51-a813-f570df298465 is now in state PROVISIONED
DEBUG 2023-09-27T10:43:32.93693199 TransferProcess f745da66-3b04-4a51-a813-f570df298465 is now in state STARTING
DEBUG 2023-09-27T10:43:32.94420589 TransferProcess: ID f745da66-3b04-4a51-a813-f570df298465. Initiate data flow
DEBUG 2023-09-27T10:43:33.109949642 TransferProcess: ID f745da66-3b04-4a51-a813-f570df298465. Send TransferStartMessage to http://localhost:9020/protocol
DEBUG 2023-09-27T10:43:33.145010864 TransferProcess: ID f745da66-3b04-4a51-a813-f570df298465. Send TransferStartMessage to http://localhost:9020/protocol
```
</details>


<details>
<summary>Provider DP logs</summary>

```
[...]
DEBUG 2023-09-27T10:43:33.081614139 DataFlow f745da66-3b04-4a51-a813-f570df298465 is now in state RECEIVED
DEBUG 2023-09-27T10:43:33.143484932 DataFlow: ID f745da66-3b04-4a51-a813-f570df298465. start data flow
DEBUG 2023-09-27T10:43:33.144291921 Transferring from HttpData to HttpData.
DEBUG 2023-09-27T10:43:33.150081353 Executing HTTP request: https://samples.openweathermap.org/data/2.5/weather?q=London&appi
DEBUG 2023-09-27T10:43:33.707466564 DataFlow f745da66-3b04-4a51-a813-f570df298465 is now in state COMPLETED
SEVERE 2023-09-27T10:43:49.982562757 Failed to send callback request
org.eclipse.edc.spi.http.EdcHttpClientException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:9191
        at org.eclipse.edc.spi.http.FallbackFactories.lambda$retryWhenStatusIsNot$3(FallbackFactories.java:60)
        at dev.failsafe.Fallback.lambda$builderOfException$0(Fallback.java:106)
        at dev.failsafe.internal.FallbackImpl.apply(FallbackImpl.java:58)
        at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:62)
        at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
        at dev.failsafe.CallImpl.execute(CallImpl.java:33)
        at dev.failsafe.okhttp.FailsafeCall.execute(FailsafeCall.java:121)
        at org.eclipse.edc.connector.core.base.EdcHttpClientImpl.execute(EdcHttpClientImpl.java:59)
        at org.eclipse.edc.connector.api.client.transferprocess.TransferProcessHttpClient.sendRequest(TransferProcessHttpClie
        at org.eclipse.edc.connector.api.client.transferprocess.TransferProcessHttpClient.completed(TransferProcessHttpClient
        at org.eclipse.edc.connector.dataplane.framework.manager.DataPlaneManagerImpl.processCompleted(DataPlaneManagerImpl.java:163)
        at org.eclipse.edc.spi.telemetry.Telemetry.lambda$contextPropagationMiddleware$0(Telemetry.java:73)
        at org.eclipse.edc.statemachine.ProcessorImpl.lambda$process$1(ProcessorImpl.java:55)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
        at org.eclipse.edc.statemachine.ProcessorImpl.process(ProcessorImpl.java:62)
        at java.base/java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:231)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:498)
        at java.base/java.util.stream.LongPipeline.sum(LongPipeline.java:456)
        at org.eclipse.edc.statemachine.StateMachineManager.performLogic(StateMachineManager.java:110)
        at org.eclipse.edc.statemachine.StateMachineManager.lambda$loop$2(StateMachineManager.java:101)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
DEBUG 2023-09-27T10:43:49.986177746 DataFlow f745da66-3b04-4a51-a813-f570df298465 is now in state NOTIFIED
```
</details>


<details>
<summary>Consumer CP logs</summary>

```
[...]
DEBUG 2023-09-27T10:43:01.621189577 [CONSUMER] ContractNegotiation f99d59b4-16bc-4c81-a69e-28cb3809b7a0 is now in state INITI
DEBUG 2023-09-27T10:43:02.201650128 [CONSUMER] ContractNegotiation f99d59b4-16bc-4c81-a69e-28cb3809b7a0 is now in state REQUE
DEBUG 2023-09-27T10:43:02.207487636 ContractNegotiation: ID f99d59b4-16bc-4c81-a69e-28cb3809b7a0. [Consumer] Send ContractReq
DEBUG 2023-09-27T10:43:02.275085174 ContractNegotiation: ID f99d59b4-16bc-4c81-a69e-28cb3809b7a0. [Consumer] Send ContractReq
DEBUG 2023-09-27T10:43:02.281970106 [CONSUMER] ContractNegotiation f99d59b4-16bc-4c81-a69e-28cb3809b7a0 is now in state REQUE
DEBUG 2023-09-27T10:43:02.488153554 DSP: Incoming ContractAgreementMessage for class org.eclipse.edc.connector.contract.spi.t
DEBUG 2023-09-27T10:43:02.514223423 [CONSUMER] ContractNegotiation f99d59b4-16bc-4c81-a69e-28cb3809b7a0 is now in state AGREE
DEBUG 2023-09-27T10:43:03.249164386 [CONSUMER] ContractNegotiation f99d59b4-16bc-4c81-a69e-28cb3809b7a0 is now in state VERIF
DEBUG 2023-09-27T10:43:03.253570697 ContractNegotiation: ID f99d59b4-16bc-4c81-a69e-28cb3809b7a0. [consumer] send ContractAgr
DEBUG 2023-09-27T10:43:03.276925521 ContractNegotiation: ID f99d59b4-16bc-4c81-a69e-28cb3809b7a0. [consumer] send ContractAgreementVerificationMessage
DEBUG 2023-09-27T10:43:03.282971619 [CONSUMER] ContractNegotiation f99d59b4-16bc-4c81-a69e-28cb3809b7a0 is now in state VERIFIED.
DEBUG 2023-09-27T10:43:03.515167934 DSP: Incoming ContractNegotiationEventMessage for class org.eclipse.edc.connector.contract.spi.types.negotiation.ContractNegotiation process: f99d59b4-16bc-4c81-a69e-28cb3809b7a0
DEBUG 2023-09-27T10:43:03.524998618 [CONSUMER] ContractNegotiation f99d59b4-16bc-4c81-a69e-28cb3809b7a0 is now in state FINALIZED.
DEBUG 2023-09-27T10:43:31.659918932 TransferProcess 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e is now in state INITIAL
DEBUG 2023-09-27T10:43:31.661382487 Process 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e is now INITIAL
DEBUG 2023-09-27T10:43:31.664523223 Transfer Process created 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e
DEBUG 2023-09-27T10:43:32.303722661 TransferProcess 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e is now in state PROVISIONING
DEBUG 2023-09-27T10:43:32.315659272 TransferProcess: ID 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e. Provisioning
DEBUG 2023-09-27T10:43:32.325766725 TransferProcess 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e is now in state PROVISIONED
DEBUG 2023-09-27T10:43:32.334825599 TransferProcess 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e is now in state REQUESTING
DEBUG 2023-09-27T10:43:32.346070216 TransferProcess: ID 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e. Send TransferRequestMessage to http://localhost:8020/protocol
DEBUG 2023-09-27T10:43:32.386757795 TransferProcess: ID 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e. Send TransferRequestMessage to http://localhost:8020/protocol
DEBUG 2023-09-27T10:43:32.392933075 TransferProcess 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e is now in state REQUESTED
DEBUG 2023-09-27T10:43:33.1183232 DSP: Incoming TransferStartMessage for class org.eclipse.edc.connector.transfer.spi.types.TransferProcess process: 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e
DEBUG 2023-09-27T10:43:33.135469559 TransferProcess 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e is now in state STARTED
WARNING 2023-09-27T10:43:33.376177103 No checker found for process 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e. The process will not advance to the COMPLETED state.
WARNING 2023-09-27T10:43:34.391731707 No checker found for process 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e. The process will not advance to the COMPLETED state.
WARNING 2023-09-27T10:43:35.417958899 No checker found for process 92f10dc4-ce0e-4f9c-badb-c2ea1c53a81e. The process will not advance to the COMPLETED state.
[...]
```
</details>

Consumer DP logs are _empty_

**Comment by wolf4ood** [comment]
Hi @timdahlmanns  by default the CP control API url is resolved using internal mechanism. For more complex scenario you should probably configure it with the property `edc.control.endpoint` which is the URL of the `CP control API`

It was added here

https://github.com/eclipse-edc/Connector/pull/3389

Still need to add this to the docs yet

**Comment by timdahlmanns** [comment]
It works now, but I still get some errors. I added the following configuration:

DP:
```properties
edc.control.endpoint=http://localhost:9050/control
```

CP (I guessed the keys to configure the control api):
```properties
web.http.control.port=9050
web.http.control.path=/control
```

The transfer process now transitions in the COMPLETED state but the the consumer DP still shows the warning:

_Consumer DP logs_

```
DEBUG 2023-09-27T13:04:13.583462281 TransferProcess 8ecc62bd-61ac-449e-8268-89ac0f120ccb is now in state INITIAL
DEBUG 2023-09-27T13:04:13.583744743 Process 8ecc62bd-61ac-449e-8268-89ac0f120ccb is now INITIAL
DEBUG 2023-09-27T13:04:13.584781398 Transfer Process created 8ecc62bd-61ac-449e-8268-89ac0f120ccb
DEBUG 2023-09-27T13:04:14.317023304 TransferProcess 8ecc62bd-61ac-449e-8268-89ac0f120ccb is now in state PROVISIONING
DEBUG 2023-09-27T13:04:14.323267013 TransferProcess: ID 8ecc62bd-61ac-449e-8268-89ac0f120ccb. Provisioning
DEBUG 2023-09-27T13:04:14.332204238 TransferProcess 8ecc62bd-61ac-449e-8268-89ac0f120ccb is now in state PROVISIONED
DEBUG 2023-09-27T13:04:14.33831434 TransferProcess 8ecc62bd-61ac-449e-8268-89ac0f120ccb is now in state REQUESTING
DEBUG 2023-09-27T13:04:14.343017365 TransferProcess: ID 8ecc62bd-61ac-449e-8268-89ac0f120ccb. Send TransferRequestMessage to http://localhost:8020/protocol
DEBUG 2023-09-27T13:04:14.375797526 TransferProcess: ID 8ecc62bd-61ac-449e-8268-89ac0f120ccb. Send TransferRequestMessage to http://localhost:8020/protocol
DEBUG 2023-09-27T13:04:14.380670032 TransferProcess 8ecc62bd-61ac-449e-8268-89ac0f120ccb is now in state REQUESTED
DEBUG 2023-09-27T13:04:15.206235814 DSP: Incoming TransferStartMessage for class org.eclipse.edc.connector.transfer.spi.types.TransferProcess process: 8ecc62bd-61ac-449e-8268-89ac0f120ccb
DEBUG 2023-09-27T13:04:15.216581378 TransferProcess 8ecc62bd-61ac-449e-8268-89ac0f120ccb is now in state STARTED
WARNING 2023-09-27T13:04:15.369419369 No checker found for process 8ecc62bd-61ac-449e-8268-89ac0f120ccb. The process will not advance to the COMPLETED state.
WARNING 2023-09-27T13:04:16.390434349 No checker found for process 8ecc62bd-61ac-449e-8268-89ac0f120ccb. The process will not advance to the COMPLETED state.
DEBUG 2023-09-27T13:04:17.242528118 DSP: Incoming TransferCompletionMessage for class org.eclipse.edc.connector.transfer.spi.types.TransferProcess process: 8ecc62bd-61ac-449e-8268-89ac0f120ccb
DEBUG 2023-09-27T13:04:17.250205977 TransferProcess 8ecc62bd-61ac-449e-8268-89ac0f120ccb is now in state COMPLETED
```


And the callback request from provider DP to provider CP returns 409 because it is already completed (my interpretation of the logs).

_Consumer DP logs_

```
DEBUG 2023-09-27T13:04:15.184370637 DataFlow c0e48423-43e8-4c7b-8b0b-f1e62cc9da4e is now in state RECEIVED
DEBUG 2023-09-27T13:04:15.828921481 DataFlow: ID c0e48423-43e8-4c7b-8b0b-f1e62cc9da4e. start data flow
DEBUG 2023-09-27T13:04:15.829439541 Transferring from HttpData to HttpData.
DEBUG 2023-09-27T13:04:15.832967449 Executing HTTP request: https://samples.openweathermap.org/data/2.5/weather?q=London&appid=b1b15e88fa797225412429c1c50c122a1
DEBUG 2023-09-27T13:04:16.350136269 DataFlow c0e48423-43e8-4c7b-8b0b-f1e62cc9da4e is now in state COMPLETED
SEVERE 2023-09-27T13:04:32.801471826 Failed to send callback request
org.eclipse.edc.spi.http.EdcHttpClientException: Server response to Request{method=POST, url=http://localhost:8050/control/transferprocess/c0e48423-43e8-4c7b-8b0b-f1e62cc9da4e/complete} was not 200 but was 409: [{"message":"Could not execute CompleteTransferCommand on TransferProcess with ID [c0e48423-43e8-4c7b-8b0b-f1e62cc9da4e] because it's COMPLETED","type":"ObjectConflict","path":null,"invalidValue":null}]
        at org.eclipse.edc.spi.http.FallbackFactories.lambda$retryWhenStatusIsNot$3(FallbackFactories.java:62)
        at dev.failsafe.Fallback.lambda$builderOfException$0(Fallback.java:106)
        at dev.failsafe.internal.FallbackImpl.apply(FallbackImpl.java:58)
        at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:62)
        at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
        at dev.failsafe.CallImpl.execute(CallImpl.java:33)
        at dev.failsafe.okhttp.FailsafeCall.execute(FailsafeCall.java:121)
        at org.eclipse.edc.connector.core.base.EdcHttpClientImpl.execute(EdcHttpClientImpl.java:59)
        at org.eclipse.edc.connector.api.client.transferprocess.TransferProcessHttpClient.sendRequest(TransferProcessHttpClient.java:66)
        at org.eclipse.edc.connector.api.client.transferprocess.TransferProcessHttpClient.completed(TransferProcessHttpClient.java:53)
        at org.eclipse.edc.connector.dataplane.framework.manager.DataPlaneManagerImpl.processCompleted(DataPlaneManagerImpl.java:163)
        at org.eclipse.edc.spi.telemetry.Telemetry.lambda$contextPropagationMiddleware$0(Telemetry.java:73)
```

**Comment by wolf4ood** [comment]
@timdahlmanns 

yes there was another fixed issue which caused unwanted retry. So if it works you can ignore this 409

[This](https://github.com/eclipse-edc/Connector/pull/3471) is the fix and it will be available in the next hotfix release

**Comment by wolf4ood** [comment]
For the warning consumer side you will still continue to see them until the notification provider -> consumer is sent for the transfer completion. At least until [this](https://github.com/eclipse-edc/Connector/issues/3448) is implemented

**Comment by timdahlmanns** [comment]
Okay, thanks for the clarification @wolf4ood :+1:

**Comment by florianrusch-zf** [comment]
I have two general question about the "Completed" state für HTTP transfers:

- what exactly does this state mean? do we have a description about the different states? would be maybe also good for the end users which are just using the EDC.
- Will the transition to the completed state have some consequences? like e.q. you can not do another request with the same EDR token or something like that?

**Comment by ndr-brt** [comment]
> I have two general question about the "Completed" state für HTTP transfers:
> 
> * what exactly does this state mean? do we have a description about the different states? would be maybe also good for the end users which are just using the EDC.
> * Will the transition to the completed state have some consequences? like e.q. you can not do another request with the same EDR token or something like that?

for the "consumer pull" transfer, the `COMPLETE` state is just a formality: once the token is expired, the transfer is implicitly completed, no other requests cannot be made on it.
